// @ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import {useFrame} from "@react-three/fiber";

const objectColor = "#5D3FD3"

export function Model(props) {
    const group = useRef();
    const { nodes, materials } = useGLTF('https://utfs.io/f/LKZsvLfoQfF7rZYhZJUnAYBO3hKUuDQRyNwTCa1GPSIblZtq')
    useFrame(() => {
        if (group.current && !props.isActive) {
            group.current.rotation.z += 0.01; // Adjust the rotation speed as needed

        }
    });

    Object.values(materials).forEach(material => {
        material.color.set(objectColor);
    });
    return (
        <group ref={group} {...props} dispose={null} scale={[300, 300, 300]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh0_mesh.geometry}
                material={materials['0.615686_0.811765_0.929412_0.000000_0.000000']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh0_mesh_1.geometry}
                material={materials['0.615686_0.811765_0.929412_0.000000_0.000000']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh0_mesh_2.geometry}
                material={materials['0.615686_0.811765_0.929412_0.000000_0.000000']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh0_mesh_3.geometry}
                material={materials['0.615686_0.811765_0.929412_0.000000_0.000000']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh0_mesh_4.geometry}
                material={materials['0.615686_0.811765_0.929412_0.000000_0.000000']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh0_mesh_5.geometry}
                material={materials['0.615686_0.811765_0.929412_0.000000_0.000000']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh0_mesh_6.geometry}
                material={materials['0.615686_0.811765_0.929412_0.000000_0.000000']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh0_mesh_7.geometry}
                material={materials['0.615686_0.811765_0.929412_0.000000_0.000000']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh0_mesh_8.geometry}
                material={materials['0.615686_0.811765_0.929412_0.000000_0.000000']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh0_mesh_9.geometry}
                material={materials['0.615686_0.811765_0.929412_0.000000_0.000000']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh0_mesh_10.geometry}
                material={materials['0.615686_0.811765_0.929412_0.000000_0.000000']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh0_mesh_11.geometry}
                material={materials['0.615686_0.811765_0.929412_0.000000_0.000000']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh0_mesh_12.geometry}
                material={materials['0.615686_0.811765_0.929412_0.000000_0.000000']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh0_mesh_13.geometry}
                material={materials['0.615686_0.811765_0.929412_0.000000_0.000000']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh0_mesh_14.geometry}
                material={materials['0.615686_0.811765_0.929412_0.000000_0.000000']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh0_mesh_15.geometry}
                material={materials['0.615686_0.811765_0.929412_0.000000_0.000000']}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mesh0_mesh_16.geometry}
                material={materials['0.615686_0.811765_0.929412_0.000000_0.000000']}
            />
        </group>
    )
}

